language: php

php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
 - mkdir -p build/logs
 - php vendor/bin/phpunit -c phpunit.xml

after_success:
 - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'